# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sleep_state_detection',
                'doc_host': 'https://ChrisRichardMiles.github.io',
                'git_url': 'https://github.com/ChrisRichardMiles/sleep_state_detection',
                'lib_path': 'sleep_state_detection'},
  'syms': {'sleep_state_detection.core': {'sleep_state_detection.core.foo': ('core.html#foo', 'sleep_state_detection/core.py')}}}
